// AUTO-GENERATED by scripts/generate-image-manifests.mjs — do not edit by hand.
// Regenerated automatically on `next dev` / `next build`. Add or remove image
// files in this folder and re-run dev/build to update this file.
import type { StaticImageData } from "next/image";

export interface ManifestEntry {
  image: StaticImageData;
  fileName: string;
}

import img_0_carousel_1_together from "./carousel-1-together.jpg";
import img_1_carousel_2_conversation from "./carousel-2-conversation.jpg";
import img_2_carousel_3_compassion from "./carousel-3-compassion.jpg";
import img_3_carousel_4_hope from "./carousel-4-hope.jpg";
import img_4_carousel_5_growth from "./carousel-5-growth.jpg";

export const images: ManifestEntry[] = [
  { image: img_0_carousel_1_together, fileName: "carousel-1-together.jpg" },
  { image: img_1_carousel_2_conversation, fileName: "carousel-2-conversation.jpg" },
  { image: img_2_carousel_3_compassion, fileName: "carousel-3-compassion.jpg" },
  { image: img_3_carousel_4_hope, fileName: "carousel-4-hope.jpg" },
  { image: img_4_carousel_5_growth, fileName: "carousel-5-growth.jpg" },
];
