// AUTO-GENERATED by scripts/generate-image-manifests.mjs — do not edit by hand.
// Regenerated automatically on `next dev` / `next build`. Add or remove image
// files in this folder and re-run dev/build to update this file.
import type { StaticImageData } from "next/image";

export interface ManifestEntry {
  image: StaticImageData;
  fileName: string;
}

import img_0_gallery_1_quiet_morning from "./gallery-1-quiet-morning.jpg";
import img_1_gallery_2_circle_of_support from "./gallery-2-circle-of-support.jpg";
import img_2_gallery_3_gentle_waves from "./gallery-3-gentle-waves.jpg";
import img_3_gallery_4_rooted_and_growing from "./gallery-4-rooted-and-growing.jpg";
import img_4_gallery_5_shared_light from "./gallery-5-shared-light.jpg";
import img_5_gallery_6_breathing_space from "./gallery-6-breathing-space.jpg";
import img_6_gallery_7_new_beginnings from "./gallery-7-new-beginnings.jpg";
import img_7_gallery_8_steady_hands from "./gallery-8-steady-hands.jpg";

export const images: ManifestEntry[] = [
  { image: img_0_gallery_1_quiet_morning, fileName: "gallery-1-quiet-morning.jpg" },
  { image: img_1_gallery_2_circle_of_support, fileName: "gallery-2-circle-of-support.jpg" },
  { image: img_2_gallery_3_gentle_waves, fileName: "gallery-3-gentle-waves.jpg" },
  { image: img_3_gallery_4_rooted_and_growing, fileName: "gallery-4-rooted-and-growing.jpg" },
  { image: img_4_gallery_5_shared_light, fileName: "gallery-5-shared-light.jpg" },
  { image: img_5_gallery_6_breathing_space, fileName: "gallery-6-breathing-space.jpg" },
  { image: img_6_gallery_7_new_beginnings, fileName: "gallery-7-new-beginnings.jpg" },
  { image: img_7_gallery_8_steady_hands, fileName: "gallery-8-steady-hands.jpg" },
];
