// AUTO-GENERATED by scripts/generate-blog-manifest.mjs — do not edit by hand.
// Regenerated automatically on `next dev` / `next build`. To publish a post,
// add a folder under src/content/blogs/ containing one .json file and one
// image file, then re-run dev/build.
import type { StaticImageData } from "next/image";

export interface BlogPost {
  slug: string;
  image: StaticImageData;
  imageAlt: string;
  title: string;
  excerpt: string;
  date: string;
  author: string;
  readTime: string;
  tags: string[];
  content: string[];
}

import post_0_understanding_anxiety_image from "./understanding-anxiety/cover.jpg";
import post_1_breaking_the_stigma_image from "./breaking-the-stigma/cover.jpg";
import post_2_supporting_a_loved_one_through_recovery_image from "./supporting-a-loved-one-through-recovery/cover.jpg";

export const posts: BlogPost[] = [
  {
    slug: "understanding-anxiety",
    image: post_0_understanding_anxiety_image,
    imageAlt: "A person sitting quietly by a window, taking a calm breath",
    title: "Understanding Anxiety: When Everyday Worry Becomes a Struggle",
    excerpt: "Anxiety is one of the most common mental health experiences — but there's a real difference between everyday stress and something that needs support. Here's how to tell them apart.",
    date: "2026-06-12",
    author: "Dr. Ritu Sen",
    readTime: "5 min read",
    tags: ["Mental Health","Anxiety"],
    content: ["Almost everyone feels anxious sometimes — before an exam, a big conversation, or a change in life. That kind of worry is normal, and it usually passes once the moment does. Anxiety becomes something else when it lingers, shows up without a clear trigger, or starts shaping the choices you make each day.","Clinically, anxiety can look like a racing heart, tight chest, trouble sleeping, or a mind that won't stop rehearsing worst-case scenarios. It can also be quieter than that: a constant low hum of unease, a reluctance to commit to plans, or exhaustion that doesn't match how little you've actually done.","The most useful question isn't 'am I anxious' — almost everyone is, at some point — but 'is this anxiety getting in the way of my life.' If worry is costing you sleep, relationships, or the ability to do things you used to enjoy, that's the signal to reach out rather than wait it out.","Support for anxiety isn't one-size-fits-all. For some people it's talk therapy and learning to recognize thought patterns before they spiral. For others it includes breathing and grounding techniques, lifestyle changes, or medication alongside counseling. A good clinician will help you figure out what combination actually fits your life.","If any of this sounds familiar, you don't need a crisis to justify asking for help. Early support is often the difference between a hard season and a long one — and at Asha Foundation, that conversation can start whenever you're ready for it."],
  },
  {
    slug: "breaking-the-stigma",
    image: post_1_breaking_the_stigma_image,
    imageAlt: "Two people sitting together in an open, sunlit conversation",
    title: "Breaking the Stigma: Why Talking About Mental Health Matters",
    excerpt: "Silence around mental health keeps people from seeking help until things are already difficult. Small, repeated conversations are how that silence breaks.",
    date: "2026-05-28",
    author: "Asha Foundation Team",
    readTime: "4 min read",
    tags: ["Awareness","Community"],
    content: ["In many families and communities, mental health is still something spoken about in whispers, if it's spoken about at all. People worry about being judged, misunderstood, or treated differently — so they carry things alone that were never meant to be carried alone.","That silence has a cost. People wait longer to ask for help. Warning signs get dismissed as 'just a phase' or 'just stress.' And the people struggling most are often the ones least likely to bring it up first, because they're the ones most afraid of how it will be received.","Stigma doesn't break with one big conversation — it wears down through many small ones. A parent who says 'it's okay to see a counselor.' A friend who asks 'how are you, really?' and waits for the honest answer. A workplace that treats a mental health day the same as a sick day.","You don't need to be an expert to help someone feel less alone. Often the most powerful thing you can offer is simply not flinching when someone tells you the truth about how they're doing — and gently pointing them toward support instead of trying to fix it yourself.","At Asha Foundation, we see every day how much easier healing becomes once someone feels safe enough to say the hard thing out loud. Part of our work is the counseling itself; the other part is helping communities become places where reaching out isn't seen as weakness, but as strength."],
  },
  {
    slug: "supporting-a-loved-one-through-recovery",
    image: post_2_supporting_a_loved_one_through_recovery_image,
    imageAlt: "A family sitting close together, offering quiet support to one another",
    title: "Supporting a Loved One Through Recovery",
    excerpt: "Recovery from addiction or mental illness rarely happens in isolation. Here's how families can offer steady, informed support without losing themselves in the process.",
    date: "2026-04-15",
    author: "Dr. Arjun Mehta",
    readTime: "6 min read",
    tags: ["Family Support","Recovery"],
    content: ["When someone you love is going through recovery — from addiction, a mental health crisis, or both — it's natural to want to fix things quickly. But recovery is rarely a straight line, and the most helpful thing a family member can offer is steady, patient presence rather than pressure to 'just get better.'","Educate yourself about what your loved one is actually going through. Addiction and many mental health conditions are medical and psychological, not failures of willpower. Understanding that changes how you respond to setbacks — with concern instead of blame.","Set boundaries that protect your own wellbeing too. Supporting someone doesn't mean absorbing every consequence of their struggle. Boundaries — around communication, finances, or your own time — actually make it possible to stay present for the long run instead of burning out.","Celebrate small progress. Recovery is made of small, unglamorous wins: a difficult conversation had honestly, a session attended, a hard day gotten through without relapse. Recognizing these moments, rather than only noticing setbacks, helps rebuild the confidence recovery depends on.","And don't do it alone. Family counseling, support groups, and open communication with your loved one's care team all exist because recovery affects the whole household, not just one person. Asha Foundation's family counseling program is built around exactly this — helping everyone involved heal together."],
  },
];
